/*
 * ipa2vec_ui — Win32 GUI wrapper for the ipa2vec / vec2ipa / vec4ipa tools.
 *
 * Framework:
 *   - main window with menu bar (File, Help), a read-only info/edit area,
 *     and a status bar
 *   - File > Export command lines…  shows the three CLI invocations for
 *     the current configuration; copy to clipboard or save as a .bat
 *
 * Build:
 *   gcc -O2 -municode -mwindows src/ipa2vec_ui.c -o ipa2vec_ui.exe \
 *       -lcomctl32 -lcomdlg32
 */

#ifndef _WIN32
#define UNICODE
#define _UNICODE
#endif
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <commdlg.h>
#include <shlwapi.h>
#include <stdio.h>

#define APP_NAME      L"IPA2Vector Workbench"
#define APP_VERSION   L"0.1.0"

#define IDC_INFO_EDIT 1001
#define IDC_EXPORT_TEXT 2001
#define IDC_EXPORT_COPY 2002
#define IDC_EXPORT_SAVE 2003
#define IDC_EXPORT_CLOSE 2004

#define ID_FILE_EXPORT 4001
#define ID_FILE_EXIT   4002
#define ID_HELP_ABOUT  4003
#define IDI_APP        101

static HWND g_hwnd = NULL;
static HWND g_hStatus = NULL;
static HFONT g_font = NULL;

/* ------------------------------------------------------------------ */
/* command-line export                                                */
/* ------------------------------------------------------------------ */

/* Build the three command lines for the current directory. */
static void build_export_text(wchar_t *buf, size_t cap)
{
    wchar_t dir[MAX_PATH];
    GetCurrentDirectoryW(MAX_PATH, dir);

    swprintf(buf, cap,
        L"# IPA2Vector CLI commands (generated by %s)\r\n"
        L"# working directory: %s\r\n"
        L"\r\n"
        L":: ipa2vec  - IPA -> 16-D vectors (with IR + rebuilt demo)\r\n"
        L"ipa2vec.exe --width 3 -i \"\\\"\\u02c8t\\u02b0a\\\"\"\r\n"
        L"\r\n"
        L":: vec2ipa  - 16-D vector -> IPA (reverse fit)\r\n"
        L"vec2ipa.exe --width 3 \"0.0,0.0,0.55,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,1.0\"\r\n"
        L"\r\n"
        L":: vec4ipa - inventory / query / reverse\r\n"
        L"vec4ipa.exe -q \u02b0\r\n"
        L"vec4ipa.exe --width 3 -r \"0.0,0.0,0.55,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,1.0\"\r\n",
        APP_VERSION, dir);
}

static void copy_to_clipboard(HWND owner, const wchar_t *text)
{
    if (!OpenClipboard(owner)) return;
    EmptyClipboard();
    size_t n = (wcslen(text) + 1) * sizeof(wchar_t);
    HGLOBAL h = GlobalAlloc(GMEM_MOVEABLE, n);
    if (h) {
        wchar_t *dst = (wchar_t *)GlobalLock(h);
        wcscpy_s(dst, n / sizeof(wchar_t), text);
        GlobalUnlock(h);
        SetClipboardData(CF_UNICODETEXT, h);
    }
    CloseClipboard();
}

static void save_bat_dialog(HWND owner, const wchar_t *text)
{
    wchar_t path[MAX_PATH] = L"ipa2vec-commands.bat";
    OPENFILENAMEW ofn;
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = owner;
    ofn.lpstrFilter = L"Batch file (*.bat)\0*.bat\0All files (*.*)\0*.*\0";
    ofn.lpstrFile = path;
    ofn.nMaxFile = MAX_PATH;
    ofn.lpstrDefExt = L"bat";
    ofn.Flags = OFN_OVERWRITEPROMPT;
    if (!GetSaveFileNameW(&ofn)) return;

    FILE *f = _wfopen(path, L"w, ccs=UTF-8");
    if (!f) {
        MessageBoxW(owner, L"Could not write the file.", APP_NAME, MB_ICONERROR);
        return;
    }
    fwprintf(f, L"@echo off\r\n");
    fwprintf(f, L"%s\r\n", text);
    fclose(f);
    MessageBoxW(owner, path, L"Saved", MB_ICONINFORMATION);
}

/* export dialog — a simple popup window with an edit + buttons */
static HWND g_dlg = NULL;
static WNDPROC g_dlg_proc = NULL;

static LRESULT CALLBACK export_wndproc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_CREATE: {
        wchar_t text[2048];
        build_export_text(text, 2048);

        CreateWindowW(L"BUTTON", L"&Copy to clipboard",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            12, 10, 130, 26, hwnd, (HMENU)IDC_EXPORT_COPY,
            GetModuleHandleW(NULL), NULL);
        CreateWindowW(L"BUTTON", L"&Save as .bat",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            150, 10, 120, 26, hwnd, (HMENU)IDC_EXPORT_SAVE,
            GetModuleHandleW(NULL), NULL);
        CreateWindowW(L"BUTTON", L"&Close",
            WS_CHILD | WS_VISIBLE | BS_PUSHBUTTON,
            280, 10, 90, 26, hwnd, (HMENU)IDC_EXPORT_CLOSE,
            GetModuleHandleW(NULL), NULL);

        HWND ed = CreateWindowExW(WS_EX_CLIENTEDGE, L"EDIT", L"",
            WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_AUTOVSCROLL |
            ES_AUTOHSCROLL,
            12, 44, 0, 0, hwnd, (HMENU)IDC_EXPORT_TEXT,
            GetModuleHandleW(NULL), NULL);
        SendMessageW(ed, WM_SETFONT, (WPARAM)g_font, TRUE);
        SetWindowTextW(ed, text);
        return 0;
    }
    case WM_SIZE: {
        int w = LOWORD(lp), h = HIWORD(lp);
        SetWindowPos(GetDlgItem(hwnd, IDC_EXPORT_TEXT), NULL,
                     12, 44, w - 24, h - 56, SWP_NOZORDER);
        break;
    }
    case WM_COMMAND:
        switch (LOWORD(wp)) {
        case IDC_EXPORT_COPY: {
            wchar_t text[2048];
            GetDlgItemTextW(hwnd, IDC_EXPORT_TEXT, text, 2048);
            copy_to_clipboard(hwnd, text);
            break;
        }
        case IDC_EXPORT_SAVE: {
            wchar_t text[2048];
            GetDlgItemTextW(hwnd, IDC_EXPORT_TEXT, text, 2048);
            save_bat_dialog(hwnd, text);
            break;
        }
        case IDC_EXPORT_CLOSE:
            DestroyWindow(hwnd);
            break;
        }
        break;
    case WM_CLOSE:
        DestroyWindow(hwnd);
        break;
    case WM_DESTROY:
        g_dlg = NULL;
        break;
    default:
        return DefWindowProcW(hwnd, msg, wp, lp);
    }
    return 0;
}

static void show_export_dialog(HWND owner)
{
    if (g_dlg) {
        SetForegroundWindow(g_dlg);
        return;
    }
    g_dlg = CreateWindowExW(WS_EX_DLGMODALFRAME, L"IPA2VecExportDlg",
        L"Export command lines", WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU,
        CW_USEDEFAULT, CW_USEDEFAULT, 460, 320,
        owner, NULL, GetModuleHandleW(NULL), NULL);
    if (g_dlg)
        ShowWindow(g_dlg, SW_SHOW);
}

/* ------------------------------------------------------------------ */
/* main window                                                        */
/* ------------------------------------------------------------------ */

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    switch (msg) {
    case WM_CREATE: {
        /* info/edit area */
        HWND ed = CreateWindowExW(WS_EX_CLIENTEDGE, L"EDIT", L"",
            WS_CHILD | WS_VISIBLE | ES_MULTILINE | ES_AUTOVSCROLL |
            ES_AUTOHSCROLL | ES_READONLY,
            0, 0, 0, 0, hwnd, (HMENU)IDC_INFO_EDIT,
            GetModuleHandleW(NULL), NULL);
        SetWindowFont(ed, g_font, TRUE);
        SetWindowTextW(ed,
            L"IPA2Vector Workbench\r\n"
            L"===================\r\n"
            L"\r\n"
            L"Wraps the three CLI tools:\r\n"
            L"  ipa2vec   IPA -> 16-D articulatory vectors\r\n"
            L"  vec2ipa   16-D vector -> IPA (reverse fit)\r\n"
            L"  vec4ipa   inventory, query, reverse\r\n"
            L"\r\n"
            L"File > Export command lines...  shows / saves the three\r\n"
            L"CLI invocations for the current configuration.\r\n"
            L"\r\n"
            L"(Tool integration follows in a later build.)\r\n");
        /* status bar */
        g_hStatus = CreateWindowExW(0, STATUSCLASSNAMEW, L"",
            WS_CHILD | WS_VISIBLE | SBARS_SIZEGRIP,
            0, 0, 0, 0, hwnd, (HMENU)1,
            GetModuleHandleW(NULL), NULL);
        SetWindowTextW(g_hStatus, L"Ready");
        break;
    }
    case WM_SIZE: {
        int w = LOWORD(lp), h = HIWORD(lp);
        SendMessageW(g_hStatus, WM_SIZE, 0, 0);
        RECT sr;
        GetWindowRect(g_hStatus, &sr);
        int sbh = sr.bottom - sr.top;
        HWND ed = GetDlgItem(hwnd, IDC_INFO_EDIT);
        SetWindowPos(ed, NULL, 0, 0, w, h - sbh, SWP_NOZORDER);
        break;
    }
    case WM_COMMAND:
        switch (LOWORD(wp)) {
        case ID_FILE_EXPORT:
            show_export_dialog(hwnd);
            break;
        case ID_FILE_EXIT:
            DestroyWindow(hwnd);
            break;
        case ID_HELP_ABOUT:
            MessageBoxW(hwnd,
                L"IPA2Vector Workbench " APP_VERSION L"\r\n"
                L"Win32 GUI wrapper for the vec4ipa tool suite.\r\n"
                L"https://github.com/csiroqa/vec4ipa",
                L"About", MB_ICONINFORMATION);
            break;
        }
        break;
    case WM_DESTROY:
        PostQuitMessage(0);
        break;
    default:
        return DefWindowProcW(hwnd, msg, wp, lp);
    }
    return 0;
}

static void init_menu(HWND hwnd)
{
    HMENU bar = CreateMenu();
    HMENU file = CreatePopupMenu();
    AppendMenuW(file, MF_STRING, ID_FILE_EXPORT, L"&Export command lines...");
    AppendMenuW(file, MF_SEPARATOR, 0, NULL);
    AppendMenuW(file, MF_STRING, ID_FILE_EXIT, L"E&xit");
    AppendMenuW(bar, MF_POPUP, (UINT_PTR)file, L"&File");

    HMENU help = CreatePopupMenu();
    AppendMenuW(help, MF_STRING, ID_HELP_ABOUT, L"&About");
    AppendMenuW(bar, MF_POPUP, (UINT_PTR)help, L"&Help");

    SetMenu(hwnd, bar);
}

int WINAPI wWinMain(HINSTANCE hInst, HINSTANCE, PWSTR, int nCmdShow)
{
    INITCOMMONCONTROLSEX icc;
    icc.dwSize = sizeof(icc);
    icc.dwICC = ICC_BAR_CLASSES;
    InitCommonControlsEx(&icc);

    g_font = CreateFontW(-16, 0, 0, 0, FW_NORMAL, 0, 0, 0,
        DEFAULT_CHARSET, 0, 0, CLEARTYPE_QUALITY, 0,
        L"Gentium Book Plus");
    /* IPA-appropriate font: full coverage of IPA/extIPA glyphs with
     * canonical (normative) letterforms (open-tail g, tie bars, …). */

    WNDCLASSEXW wc = {0};
    wc.cbSize = sizeof(wc);
    wc.lpfnWndProc = WndProc;
    wc.hInstance = hInst;
    wc.hIcon = LoadIconW(hInst, MAKEINTRESOURCEW(IDI_APP));
    wc.hIconSm = LoadIconW(hInst, MAKEINTRESOURCEW(IDI_APP));
    wc.hCursor = LoadCursorW(NULL, (LPCWSTR)IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
    wc.lpszClassName = L"IPA2VectorWorkbench";
    RegisterClassExW(&wc);

    WNDCLASSW we = {0};
    we.lpfnWndProc = export_wndproc;
    we.hInstance = hInst;
    we.hIcon = LoadIconW(hInst, MAKEINTRESOURCEW(IDI_APP));
    we.hCursor = LoadCursorW(NULL, (LPCWSTR)IDC_ARROW);
    we.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);
    we.lpszClassName = L"IPA2VecExportDlg";
    RegisterClassW(&we);

    g_hwnd = CreateWindowExW(0, wc.lpszClassName, APP_NAME,
        WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT, 640, 480,
        NULL, NULL, hInst, NULL);
    if (!g_hwnd) return 1;

    init_menu(g_hwnd);
    ShowWindow(g_hwnd, nCmdShow);
    UpdateWindow(g_hwnd);

    MSG msg;
    while (GetMessageW(&msg, NULL, 0, 0) > 0) {
        if (!IsDialogMessageW(g_hwnd, &msg)) {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
    }
    return (int)msg.wParam;
}
